# Generated by Django 4.0.2 on 2022-05-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalappointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
