# Generated by Django 4.0.2 on 2022-05-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalappointment', '0003_doctorappointment_create_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='uodate_at',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='doctorappointment',
            old_name='uodate_at',
            new_name='update_at',
        ),
    ]
