# Generated by Django 4.0.2 on 2022-05-14 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalappointment', '0005_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactus',
        ),
    ]
