# Generated by Django 4.0.2 on 2022-05-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalappointment', '0008_customuser_password1_customuser_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password2',
        ),
    ]
