# Generated by Django 4.0.2 on 2022-05-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalappointment', '0009_remove_customuser_password1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password1',
            field=models.CharField(max_length=50, null=True, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
